project:
  type: website

website:
  title: "test-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
  body-footer: 
    footer.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

